apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello.fullname" . }}-log-exporter-config
  labels:
    app.kubernetes.io/name: {{ include "hello.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    listen:
      port: 4040
      address: "0.0.0.0"
    
    consul:
      enable: false
    
    namespaces:
      - name: nginx_app
        format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=$request_time"
        source:
          files:
            - /var/log/nginx/app_prometheus.log
        
        # Only add non-conflicting labels
        labels:
          env: "{{ .Values.environment }}"
        
        histogram_buckets: [.005, .01, .025, .05, .075, .1, .25, .5, .75, 1.0, 2.5, 5.0, 7.5, 10.0]
